### ISSUE TITLE
Doesn't build with linux kernel 5.10+

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/deepin-anything#31]
```
make: Entering directory '/build/deepin-anything-arch/src/deepin-anything-5.0.1/kernelmod'
make -C /usr/src/linux M=/build/deepin-anything-arch/src/deepin-anything-5.0.1/kernelmod modules
make[1]: Entering directory '/build/deepin-anything-arch/src/deepin-anything-5.0.1/kernelmod'
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
  CC [M]  /build/deepin-anything-arch/src/deepin-anything-5.0.1/kernelmod/vfs_utils.o
/build/deepin-anything-arch/src/deepin-anything-5.0.1/kernelmod/vfs_utils.c: In function ‘read_file_content’:
/build/deepin-anything-arch/src/deepin-anything-5.0.1/kernelmod/vfs_utils.c:26:24: error: implicit declaration of function ‘get_fs’; did you mean ‘sget_fc’? [-Werror=implicit-function-declaration]
   26 |  mm_segment_t old_fs = get_fs();
      |                        ^~~~~~
      |                        sget_fc
/build/deepin-anything-arch/src/deepin-anything-5.0.1/kernelmod/vfs_utils.c:26:24: error: invalid initializer
/build/deepin-anything-arch/src/deepin-anything-5.0.1/kernelmod/vfs_utils.c:27:2: error: implicit declaration of function ‘set_fs’; did you mean ‘sget_fc’? [-Werror=implicit-function-declaration]
   27 |  set_fs(KERNEL_DS);
      |  ^~~~~~
      |  sget_fc
/build/deepin-anything-arch/src/deepin-anything-5.0.1/kernelmod/vfs_utils.c:27:9: error: ‘KERNEL_DS’ undeclared (first use in this function); did you mean ‘KERNFS_NS’?
   27 |  set_fs(KERNEL_DS);
      |         ^~~~~~~~~
      |         KERNFS_NS
/build/deepin-anything-arch/src/deepin-anything-5.0.1/kernelmod/vfs_utils.c:27:9: note: each undeclared identifier is reported only once for each function it appears in
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:279: /build/deepin-anything-arch/src/deepin-anything-5.0.1/kernelmod/vfs_utils.o] Error 1
make[1]: *** [Makefile:1805: /build/deepin-anything-arch/src/deepin-anything-5.0.1/kernelmod] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.10.1-arch1-1/build'
make: *** [Makefile:9: all] Error 2
```

**Comment by hujianzhong-UOS** [comment]
![image](https://user-images.githubusercontent.com/76022407/102446964-f456b900-4069-11eb-9ff7-dd9dc698e27f.png)
这个功能在5.10上面不能用，内核中删除了对文件的操作

**Comment by youxiaojie** [comment]
> ![image](https://user-images.githubusercontent.com/76022407/102446964-f456b900-4069-11eb-9ff7-dd9dc698e27f.png)
> 这个功能在5.10上面不能用，内核中删除了对文件的操作

我也遇到这个问题了,编译别的项目,但是asm/uaccess.h里面有get_fs() set_fs()的宏定义啊?

**Comment by youxiaojie** [comment]
```
#ifdef CONFIG_SET_FS
/*
 * Force the uaccess routines to be wired up for actual userspace access,
 * overriding any possible set_fs(KERNEL_DS) still lingering around.  Undone
 * using force_uaccess_end below.
 */
static inline mm_segment_t force_uaccess_begin(void)
{
        mm_segment_t fs = get_fs();

        set_fs(USER_DS);
        return fs;
}

static inline void force_uaccess_end(mm_segment_t oldfs)
{
        set_fs(oldfs);
}
#else /* CONFIG_SET_FS */
typedef struct {
        /* empty dummy */
} mm_segment_t;

```
I met this questions too!
two new function defined in linux/uaccess.h, should we use these two functions instead fs_get() fs_set()?
however mm/maccess.c use a lot of fs_get fs_set, compiled ok? why!!!!

**Comment by youxiaojie** [comment]
使用 force_uaccess_begin(), force_uaccess_end(), linux/uaccess.h中定义

**Comment by deepin-CD** [comment]
这个只有在linux5.10内核以后才会有这样的问题

**Comment by justforlxz** [comment]
This is a patch that has not been merged, and we think it can solve the problem. (Still unresolved vfs_monitor loading)

```
diff --git a/debian/changelog b/debian/changelog
index 94f2361..7876d60 100644
--- a/debian/changelog
+++ b/debian/changelog
@@ -1,3 +1,9 @@
+deepin-anything (5.0.2+dde) unstable; urgency=medium
+
+  * add support for Linux 5.10.
+
+ -- Deepin Package Builder <lichenggang@uniontech.com>  Thu, 24 Dec 2020 17:17:33 +0800
+
 deepin-anything (20180315+1) unstable; urgency=medium
 
   * Initial release.
diff --git a/kernelmod/vfs_utils.c b/kernelmod/vfs_utils.c
index 2549e10..75139dd 100644
--- a/kernelmod/vfs_utils.c
+++ b/kernelmod/vfs_utils.c
@@ -6,6 +6,7 @@
 #include <linux/slab.h>
 #include <linux/uaccess.h>
 #include <linux/file.h>
+#include <linux/version.h>
 
 #include "vfs_utils.h"
 
@@ -23,9 +24,13 @@
 		pr_err("error opening %s\n", filename);
 		return 0;
 	}
-	mm_segment_t old_fs = get_fs();
-	set_fs(KERNEL_DS);
 
+#if LINUX_VERSION_CODE >= KERNEL_VERSION(5, 10, 0)
+        mm_segment_t old_fs = force_uaccess_begin();
+#else
+        mm_segment_t old_fs = get_fs();
+        set_fs(KERNEL_DS);
+#endif
 	// i_size_read is useless here because procfs does not have i_size
 	// loff_t size = i_size_read(file_inode(filp));
 	char *buf = 0;
@@ -46,7 +51,13 @@
 		size += ALLOC_UNIT;
 		kfree(buf);
 	}
-	set_fs(old_fs);
+
+#if LINUX_VERSION_CODE >= KERNEL_VERSION(5, 10, 0)
+        force_uaccess_end(old_fs);
+#else
+        set_fs(old_fs);
+#endif	
+	
 	filp_close(filp, 0);
 	// pr_info("%s size: %d\n", filename, *real_size);
 	return buf;


```

**Comment by deepin-CD** [comment]
Because the linus that is the author for the linux delete the set_fs and read_fs basing the security for the kernel,so There is no adaptation for the current version（Linux5.10）. This problem will be solved in the new version

**Comment by deepin-CD** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.

**Comment by spfanlost** [comment]
thanks !
two new function defined in linux/uaccess.h,  we should use these two functions instead fs_get() fs_set()!
