### ISSUE TITLE
Broken on kernel 5.0 because of do_gettimeofday

### ISSUE THREAD

**Issue by aedancullen** [linuxdeepin/deepin-anything#10]
`deepin-anything` fails to build on Manjaro with kernel 5.0.1; see below. 

It appears `do_gettimeofday` was deprecated and is now removed.

```
DKMS make.log for deepin-anything-0.0.4 for kernel 5.0.1-1-MANJARO (x86_64)
Tue Mar 12 17:01:21 EDT 2019
make: Entering directory '/usr/lib/modules/5.0.1-1-MANJARO/build'
Makefile:189: ================= WARNING ================
Makefile:190: 'SUBDIRS' will be removed after Linux 5.3
Makefile:191: Please use 'M=' or 'KBUILD_EXTMOD' instead
Makefile:192: ==========================================
  CC [M]  /var/lib/dkms/deepin-anything/0.0.4/build/vfs_utils.o
  CC [M]  /var/lib/dkms/deepin-anything/0.0.4/build/arg_extractor.o
  CC [M]  /var/lib/dkms/deepin-anything/0.0.4/build/vfs_kretprobes.o
  CC [M]  /var/lib/dkms/deepin-anything/0.0.4/build/vfs_change.o
/var/lib/dkms/deepin-anything/0.0.4/build/vfs_change.c: In function ‘vfs_changed’:
/var/lib/dkms/deepin-anything/0.0.4/build/vfs_change.c:588:2: error: implicit declaration of function ‘do_gettimeofday’; did you mean ‘do_settimeofday64’? [-Werror=implicit-function-declaration]
  do_gettimeofday(&vc->ts);
  ^~~~~~~~~~~~~~~
  do_settimeofday64
cc1: some warnings being treated as errors
make[1]: *** [scripts/Makefile.build:276: /var/lib/dkms/deepin-anything/0.0.4/build/vfs_change.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:1553: _module_/var/lib/dkms/deepin-anything/0.0.4/build] Error 2
make: Leaving directory '/usr/lib/modules/5.0.1-1-MANJARO/build'
```

**Comment by jlnhab** [comment]
Same here with fedora Kernel 5.0.3-200.fc29.x86_64
  CC [M]  /usr/src/phones/dahdi-linux-master/drivers/dahdi/oct612x/oct612x-user.o
/usr/src/phones/dahdi-linux-master/drivers/dahdi/oct612x/oct612x-user.c: In function â€˜Oct6100UserGetTimeâ€™:
/usr/src/phones/dahdi-linux-master/drivers/dahdi/oct612x/oct612x-user.c:38:2: error: implicit declaration of function â€˜do_gettimeofdayâ€™; did you mean â€˜do_settimeofday64â€™? [-Werror=implicit-function-declaration]
  do_gettimeofday(&tv);
  ^~~~~~~~~~~~~~~
  do_settimeofday64
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:277: /usr/src/phones/dahdi-linux-master/drivers/dahdi/oct612x/oct612x-user.o] Error 1
make[2]: *** [scripts/Makefile.build:492: /usr/src/phones/dahdi-linux-master/drivers/dahdi/oct612x] Error 2
make[1]: *** [Makefile:1557: _module_/usr/src/phones/dahdi-linux-master/drivers/dahdi] Error 2
make[1]: Leaving directory '/usr/src/kernels/5.0.3-200.fc29.x86_64'
make: *** [Makefile:74: modules] Error 2

**Comment by silviomm** [comment]
I was having the same problem running on Arch with kernel `5.0.7`;
Fixed after installing `linux-headers`

**Comment by kshatriya-abhay** [comment]
This was recently fixed in the package it seems.
I can't link the commit but now there's no issue in compiling (headers are obviously needed, but the error used to come despite having them)

**Comment by silviomm** [comment]
Yeah, I saw the commit(I'm guessing [this one](https://github.com/linuxdeepin/deepin-anything/commit/d3c353f11989a6221f9378b4ce7bf0608c0cd8e9)), but I didn't have headers installed(and updated) until now

**Comment by BLumia** [comment]
Probably associated: https://github.com/linuxdeepin/deepin-anything/pull/18

**Comment by Oumayma-crypto** [comment]
Hello, I'm still having the same error after installing the headers. any solution to that ?

**Comment by anglely168** [comment]
> I was having the same problem running on Arch with kernel `5.0.7`;
> Fixed after installing `linux-headers`

I met the same issue in kernel 5.4.24 when i build a driver, Can you tell me how to install the new headers files to resolve it?
