### ISSUE TITLE
This module is causing problems on patchs for Antergos and Manjaro

### ISSUE THREAD

**Issue by SchrodingerZhu** [linuxdeepin/deepin-anything#9]
`deepin-anything` package will lead to some systemd modules loading failures. The kernel version is `4.19` and `4.20`.

Here is the journal:
```
12月 27 02:22:28 schrodingerzhu-pc systemd-modules-load[345]: Failed to find module 'vfs_monitor'
12月 27 02:22:28 schrodingerzhu-pc systemd-modules-load[345]: Inserted module 'crypto_user'
12月 27 02:22:28 schrodingerzhu-pc systemd-modules-load[345]: Inserted module 'uinput'
12月 27 02:22:28 schrodingerzhu-pc systemd[1]: systemd-modules-load.service: Main process exited, code=exited, status=1/FAILURE
12月 27 02:22:28 schrodingerzhu-pc systemd[1]: systemd-modules-load.service: Failed with result 'exit-code'.
12月 27 02:22:28 schrodingerzhu-pc systemd[1]: Failed to start Load Kernel Modules.
12月 27 02:22:42 schrodingerzhu-pc systemd[1]: Starting Load Kernel Modules...
12月 27 02:22:42 schrodingerzhu-pc systemd[1]: systemd-modules-load.service: Main process exited, code=exited, status=1/FAILURE
12月 27 02:22:42 schrodingerzhu-pc systemd[1]: systemd-modules-load.service: Failed with result 'exit-code'.
12月 27 02:22:42 schrodingerzhu-pc systemd[1]: Failed to start Load Kernel Modules.
12月 27 02:22:46 schrodingerzhu-pc systemd[1]: Starting Load Kernel Modules...
12月 27 02:22:46 schrodingerzhu-pc systemd-modules-load[810]: Failed to find module 'vfs_monitor'
12月 27 02:22:46 schrodingerzhu-pc systemd[1]: systemd-modules-load.service: Main process exited, code=exited, status=1/FAILURE
12月 27 02:22:46 schrodingerzhu-pc systemd[1]: systemd-modules-load.service: Failed with result 'exit-code'.
12月 27 02:22:46 schrodingerzhu-pc systemd[1]: Failed to start Load Kernel Modules.

```
And here are the errors happened when updating hooks
```
(2/4) Install DKMS modules
==> dkms install deepin-anything/0.0.3 -k 4.20.0-1-MANJARO
Error! Bad return status for module build on kernel: 4.20.0-1-MANJARO (x86_64)
Consult /var/lib/dkms/deepin-anything/0.0.3/build/make.log for more information.
```

And this is the make.log:
```
DKMS make.log for deepin-anything-0.0.3 for kernel 4.20.0-1-MANJARO (x86_64)
四 12月 27 13:41:11 HKT 2018
make: Entering directory '/usr/lib/modules/4.20.0-1-MANJARO/build'
  CC [M]  /var/lib/dkms/deepin-anything/0.0.3/build/vfs_utils.o
  CC [M]  /var/lib/dkms/deepin-anything/0.0.3/build/arg_extractor.o
  CC [M]  /var/lib/dkms/deepin-anything/0.0.3/build/vfs_change.o
  CC [M]  /var/lib/dkms/deepin-anything/0.0.3/build/vfs_kretprobes.o
/var/lib/dkms/deepin-anything/0.0.3/build/vfs_change.c: In function ‘copy_vfs_changes’:
/var/lib/dkms/deepin-anything/0.0.3/build/vfs_change.c:118:3: error: implicit declaration of function ‘time_to_tm’; did you mean ‘time64_to_tm’? [-Werror=implicit-function-declaration]
   time_to_tm(shifted_secs, 0, &ts);
   ^~~~~~~~~~
   time64_to_tm
cc1: some warnings being treated as errors
make[1]: *** [scripts/Makefile.build:291: /var/lib/dkms/deepin-anything/0.0.3/build/vfs_change.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:1563: _module_/var/lib/dkms/deepin-anything/0.0.3/build] Error 2
make: Leaving directory '/usr/lib/modules/4.20.0-1-MANJARO/build'

```

**Comment by SchrodingerZhu** [comment]
It works by changing `time_to_tm` to `time64_to_tm`.

**Comment by aedancullen** [comment]
This was fixed and the issue can be closed.
https://github.com/linuxdeepin/deepin-anything/blob/34353bfcc680990bbb583936415e2b03434d4a93/kernelmod/vfs_change.c#L118-L122
